version: '3'
services:
  arpa:
    build: .
    ports:
      - "19991:9000"
    environment:
      - analyze_address=http://las:9000/las/analyze
    volumes:
      - ./services:/opt/arpa/services
  las:
    image: "jiemakel/las-ws:1.1"
    ports:
      - "19990:9000"
