version: '3'
services:
  arpa:
    image: "jiemakel/arpa:1.0"
    ports:
      - "19991:9000"
    environment:
      - ANALYZE_ADDRESS=http://las:9000/las/analyze
    volumes:
      - ./services:/opt/docker/services
    restart: unless-stopped
  las:
    image: "jiemakel/las-ws:1.1"
    ports:
      - "19990:9000"
    restart: unless-stopped
